Update README.md
marmelo/tech-companies-in-portugal pull request #332
Opened 2023-03-23 21:52 UTC by naboavida

Added Bitsight.

2023-03-23 23:54 UTC, marmelo commented on README.md
> +| [Bitsight](https://www.bitsight.com/) [:rocket:](https://www.bitsight.com/about/careers) | The Global Leader In Security Ratings. | `Remote` `Lisboa` |
Remote must be the last entry.

```suggestion
| [Bitsight](https://www.bitsight.com/) [:rocket:](https://www.bitsight.com/about/careers) | The Global Leader In Security Ratings. | `Lisboa` `Remote` |
```

2023-03-23 23:54 UTC, marmelo requested changes

2023-03-23 23:54 UTC, marmelo commented on README.md
> +| [Bitsight](https://www.bitsight.com/) [:rocket:](https://www.bitsight.com/about/careers) | The Global Leader In Security Ratings. | `Remote` `Lisboa` |
Remote must be the last entry.

```suggestion
| [Bitsight](https://www.bitsight.com/) [:rocket:](https://www.bitsight.com/about/careers) | The Global Leader In Security Ratings. | `Lisboa` `Remote` |
```

2023-03-24 11:05 UTC, marmelo approved these changes

2023-03-24 18:44 UTC, vpereira01 approved these changes

2023-03-24 18:44 UTC, merged