Abyssal is now Ocean Infinity
marmelo/tech-companies-in-portugal pull request #341
Opened 2023-05-31 08:34 UTC by lhugens

Abyssal is now Ocean Infinity, updated company title, url's and company description.

2023-05-31 17:14 UTC, marmelo requested changes
For context:

> Abyssal’s 38 highly experienced employees will transition to the [Ocean Infinity](https://oceaninfinity.com/) Group, and will operate from Porto, Portugal, under the Ocean Infinity brand.

2023-06-02 10:26 UTC, lhugens commented
Fixed typo.

2023-06-02 11:08 UTC, marmelo approved these changes

2023-06-02 17:47 UTC, vpereira01 approved these changes

2023-06-02 17:48 UTC, merged