Add companies
marmelo/tech-companies-in-portugal pull request #413
Opened 2024-10-31 01:38 UTC by Rxfa

Add

- Autodoc (Moved its biggest tech hub to Lisbon. See [here](https://leitor.jornaleconomico.pt/noticia/talento-portugues-trouxe-centro-tecnologico-da-autodoc-para-portugal))
- Carwow (Hiring for tech roles in Porto. See [here](https://www.carwow.co.uk/jobs#gref))
- Veeam (Hiring for tech roles in Lisbon. See [here](https://careers.veeam.com/vacancies?query=&department=&location=Portugal&state=all&city=all))
- Nextlane (hiring for tech roles in Lisbon. See [here](https://www.linkedin.com/jobs/search/?currentJobId=3780178492&f_C=100697506%2C54593&geoId=92000000&origin=COMPANY_PAGE_JOBS_CLUSTER_EXPANSION&originToLandingJobPostings=3780178492%2C3794120174%2C3776787002%2C3790060295%2C3790728705%2C3776759296%2C3789329659%2C3780116726%2C3780123080))
- TeamViewer (Hiring for tech roles in Porto. see [here](https://careers.teamviewer.com/search/?q=&q2=&alertId=&title=&location=PT))
- Dremio (Hiring for tech roles to work in their Lisbon office or remotely. See [here](https://www.dremio.com/careers/job-postings/))
- Iterable (Hiring for tech roles in Lisbon. See [here](https://iterable.com/careers/))
- Workia (Hiring for tech roles in Lisbon. See [here](https://www.linkedin.com/jobs/search/?currentJobId=4062557245&f_C=91594487&geoId=92000000&origin=COMPANY_PAGE_JOBS_CLUSTER_EXPANSION&originToLandingJobPostings=4062557245))
- Paddle (Hiring for tech roles in Lisbon. See [here](https://www.paddle.com/careers#open-positions))
- Riskified (Hiring for tech roles in Lisbon. See [here](https://www.riskified.com/careers/#positions))
- Tabby (Hiring for tech roles to work remotely from anywhere in Portugal. See [here](https://tabby.ai/en-AE/careers#careers))
- Teya (Hiring for tech roles in Lisbon and Porto. See [here](https://careers.smartrecruiters.com/Teya))
- Wallet (Hiring for tech roles to work remotely from anywhere in Portugal. See [here](https://jobs.ton.org/companies/wallet-2))
- Restream (Hiring for tech roles in Lisbon. See [here](https://restream.io/careers))

2024-10-31 19:58 UTC, vpereira01 commented
Should be added check:

- Autodoc :heavy_check_mark: 
- Carwow :heavy_check_mark: (reference sites did not had tech jobs in Portugal but linkedin/jobsites had them)
- Nextlane :heavy_check_mark: 
- Nitro :heavy_check_mark: 
- TeamViewer :heavy_check_mark: 
- Dremio :heavy_check_mark: 
- Iterable :heavy_check_mark: 
- Veeam :heavy_check_mark: 
- Workia :white_check_mark: (seems only just a brand, the parent company as the same job opening https://apply.workable.com/equus-software/j/7A20413A8B/ )
- Paddle :heavy_check_mark: 
- Riskified :heavy_check_mark: 
- Tabby :heavy_check_mark: 
- Teya :heavy_check_mark: 
- Wallet :heavy_check_mark: 
- Restream :heavy_check_mark:

2024-10-31 22:39 UTC, vpereira01 requested changes

2024-10-31 22:39 UTC, vpereira01 commented on README.md
> +| [Nextlane](https://www.nextlane.com/) [:rocket:](https://www.nextlane.com/career/) | Software solutions to optimize logistics and supply chain in the automotive industry. | `Lisboa` |
```suggestion
| [Nextlane](https://www.nextlane.com/) [:rocket:](https://www.nextlane.com/career/) | Software solutions to optimize automotive logistics and supply chain. | `Lisboa` |
```

Reduces description to max allowed chars, 70.

2024-10-31 22:39 UTC, vpereira01 commented on README.md
> +| [Nitro](https://www.gonitro.com/) [:rocket:](https://www.gonitro.com/about/careers) | Document productivity platform that simplifies PDF editing and collaboration. | `Porto` |
```suggestion
| [Nitro](https://www.gonitro.com/) [:rocket:](https://www.gonitro.com/about/careers) | Productivity platform that simplifies PDF editing and collaboration. | `Porto` |
```

Reduces description to max allowed chars, 70.

2024-10-31 22:39 UTC, vpereira01 commented on README.md
> +| [TeamViewer](https://www.teamviewer.com) [:rocket:](https://careers.teamviewer.com) | Remote access and support software for device management and collaboration. | `Porto` |
```suggestion
| [TeamViewer](https://www.teamviewer.com) [:rocket:](https://careers.teamviewer.com) | Remote access, device management and collaboration. | `Porto` |
```

Reduces description to max allowed chars, 70.

2024-10-31 22:39 UTC, vpereira01 commented on README.md
> +| [Veeam](https://www.veeam.com/) [:rocket:](https://careers.veeam.com/vacancies) | Backup, recovery, and data management solutions for businesses | `Lisboa` |
```suggestion
| [Veeam](https://www.veeam.com/) [:rocket:](https://careers.veeam.com/vacancies) | Backup, recovery, and data management solutions for businesses. | `Lisboa` |
```
adding dot at the end.

2024-10-31 22:39 UTC, vpereira01 commented on README.md
> +| [Workia](https://workia.com/en/) | Collaboration platform that boosts workplace productivity and engagement. | `Lisboa` |
```suggestion
| [Workia](https://workia.com/en/) | Simplifies the management of global employee mobility programs. | `Lisboa` |
```
Reduces description and better characterizes it

2024-10-31 22:39 UTC, vpereira01 commented on README.md
> +| [Pleo](https://www.pleo.io) [:rocket:](https://www.pleo.io/en/careers/jobs) | Smart payment cards and expense management tools for businesses | `Lisboa` `Remote` |
:+1:

2024-10-31 22:39 UTC, vpereira01 commented on README.md
> +| [Tabby](https://tabby.ai/en-AE) | Buy now, pay later platform that offers flexible payment options. | `Remote` |
```suggestion
| [Tabby](https://tabby.ai/en-AE) [:rocket:](https://tabby.ai/en-AE/careers#careers) | Buy now, pay later platform that offers flexible payment options. | `Remote` |
```

2024-11-01 17:31 UTC, vpereira01 commented on README.md
> +| [Elecnor Deimos](https://www.elecnor-deimos.com/) [:rocket:](https://www.elecnor-deimos.com/jobs/) | Advanced design solutions and turn-key space software systems. | `Lisboa` |
```suggestion
```
clean up merge mess

2024-11-01 17:33 UTC, vpereira01 approved these changes
:+1:

2024-11-02 14:48 UTC, marmelo requested changes

2024-11-02 14:48 UTC, marmelo commented on README.md
> +| [Dremio](https://www.dremio.com/) [:rocket:](https://www.dremio.com/careers/job-postings/) | data-as-a-service platform for fast analytics and data integration. | `Lisboa` `Remote` |
I believe the right way is withouth hyphens.

```suggestion
| [Dremio](https://www.dremio.com/) [:rocket:](https://www.dremio.com/careers/job-postings/) | Data as a service platform for fast analytics and data integration. | `Lisboa` `Remote` |
```

2024-11-02 14:48 UTC, marmelo commented on README.md
> +| [Riskified](https://www.riskified.com) [:rocket:](https://www.riskified.com/careers/#positions) | e-commerce fraud prevention. | `Lisboa` |
```suggestion
| [Riskified](https://www.riskified.com) [:rocket:](https://www.riskified.com/careers/#positions) | E-commerce fraud prevention. | `Lisboa` |
```

2024-11-02 19:57 UTC, afonsojramos approved these changes

2024-11-02 19:58 UTC, afonsojramos commented
That's a lot of them! Thanks!

2024-11-04 09:48 UTC, marmelo approved these changes

2024-11-04 09:49 UTC, merged

2024-11-04 09:49 UTC, marmelo commented
Thank you @Rxfa!